name: Build Latest (Windows)

on:
  push:
    branches: ["main"]

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Get Vars
        id: vars
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "filename=shader-renderer-windows-latest.zip" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: git mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-glfw

      - name: Configure
        run: cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Package
        run: Compress-Archive -Path build\output\* -DestinationPath ${{ steps.vars.outputs.filename }}
        shell: pwsh

      - name: Remove Previous Lastest Release
        run: gh release delete latest --cleanup-tag || true
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Update Tag
        run: |
          git tag latest
          git push -f origin latest
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Latest Build (${{ steps.vars.outputs.short_sha }})
          tag_name: latest
          body: Automated build from ${{ steps.vars.outputs.short_sha }}
          files: ${{ steps.vars.outputs.filename }}
